version: 2
base: &base
  docker:
    - image: dimiguel/circleci-golang
    - image: dimiguel/circleci-beanstalkd
jobs:
  build:
    <<: *base
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: v2-{{ checksum "go.mod" }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - persist_to_workspace:
          root: /root/project
          paths:
            - ./*
  test:
    <<: *base
    steps:
      - attach_workspace:
          at: /root/project
      - run: go test
workflows:
  version: 2
  default:
    jobs:
      - build
      - test:
          requires:
            - build